[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
cache_path = 'forge-cache'
remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/', 
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@superfluid-finance/=lib/protocol-monorepo/packages/',
    'erc721a-upgradeable/=lib/ERC721A-Upgradeable/'
    ]

[rpc_endpoints]
optimism-goerli = "${OPTIMISM_GOERLI_RPC}"
base-goerli = "${BASE_GOERLI_RPC}"
base-sepolia = "${BASE_SEPOLIA_RPC}"    
base = "${BASE_RPC}"

[etherscan]
optimism-goerli = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = 420 }
base-goerli = { key = "${ETHERSCAN_API_KEY}", chain = 84531, url = "https://api-goerli.basescan.org/api" }
base-sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASE_ETHERSCAN_API_KEY}", chain = 8453 }

[fuzz]
seed = "0x3130"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

