[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/', 
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@superfluid-finance/=lib/protocol-monorepo/packages/',
    'erc721a-upgradeable/=lib/ERC721A-Upgradeable/'
    ]

[rpc_endpoints]
optimism-goerli = "${OPTIMISM_GOERLI_RPC}"
base-goerli = "${BASE_GOERLI_RPC}"



# See more config options https://github.com/foundry-rs/foundry/tree/master/config