on: [push]

name: contracts-test

env:
  OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
  BASE_GOERLI_RPC: ${{ secrets.BASE_GOERLI_RPC }}

jobs:
  check:
    name: Smart Contracts Test Campaign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run test campaign
        run: forge test -vvv
